server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@
    username: 
    password: 
  freemarker:
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/ftl/

management:
  security:
    enabled: false
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
application.message: Hello Phil
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.demo.entity






