server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/test?useSSL=false&characterEncoding=utf-8
    username: root
    password: root

management:
  security:
    enabled: false
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
application.message: Hello Phil
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.demo.entity





